@startuml EducationPlatformDomain

abstract Itinerary {
    - Edition
}

interface Topic{
    + getTableOfContents()
    + getSyllabus() : Concepts
    + Edit()
    + Read()
}


class SimpleTopic{
}

class CompositeTopic{
    - topics : List<Topic> 
}

class Excercise {
    - Version :Prototype
}

class Solution {
    - Version
}

class Incorrect {
- Justification
}

class Document {
    - TableOfContents
}

class Concept {
    - isAskable()
}

class Definition {
    - isFake()
}

class Justification {
    - isFake()
}

class Relation {

}

EducationPlatform *--> "+" Teacher
EducationPlatform *--> "+" Student
EducationPlatform *--> Topic
EducationPlatform o--> "+" Itinerary
EducationPlatform o--> Asker
EducationPlatform o--> Excercise

Asker ..>"*" Excercise
Asker...> Student
Student...> Asker :Chat
 
Excercise <|-- Domain
Domain *--> Application
Domain *--> Requirement
Application --> Topic
Excercise <|-- Question
'Excercise *--> Statement
Application o-->"n" Solution
Solution <|-- Correct
Solution <|-- Incorrect

Question -->"*" Concept
Question -->"*" Solution 


Teacher ..> Topic : Editor
Teacher ..> Predefined : Editor
Student ...> Topic : Reader
Student ...> Custom : Editor


Topic <|.. CompositeTopic
Topic <|.. SimpleTopic
CompositeTopic o--> "+" Topic

Itinerary <|-- Custom
Itinerary <|-- Predefined

Custom o--> "1..n" Topic
Predefined o--> "*" Topic


SimpleTopic o--> "+" Concept
SimpleTopic o--> "+" Multimedia
Concept *--> "+" Definition
Definition o--> "*" Relation
Relation <|-- Use
Relation <|-- Association
Relation <|-- Agregation
Relation <|-- Composition
Relation <|-- Inheritance

Relation -->"+" Concept
Definition o-->"+" Justification
Justification o-->"+" Justification


Multimedia <|-- Podcast
Multimedia <|-- Video

Podcast o--> Document : transcript
Video o--> Document : transcript

Multimedia <|-- Document

Document *-->"*" Concept
Document o-->"*" Image


@enduml