@startuml EducationPlatformDomain

abstract Itinerary {
    - Edition
}

interface Topic{
    + getTableOfContents()
    + getSyllabus() : Concepts
    + Edit()
    + Read()
}


class SimpleTopic{
}

class CompositeTopic{
    - topics : List<Topic> 
}

class Excercise {
}

class Domain {
}

class Application {
    - Version
}

class Incorrect {
    - Justification
}

class Question {

}

enum Statement {
    ClozeTest
    Definition
    Relation
    JustifyApplication
}

class Document {
    - TableOfContents
}

class Concept {
}

class Definition {
    - isFalse()
}

class Justification {
    - isFalse()
}

class Relation {

}

class Multimedia {

}
note left of Multimedia
¿Asociar a otros temas?
end note

EducationPlatform *--> "+" Teacher
EducationPlatform *--> "+" Student
EducationPlatform *--> Topic
EducationPlatform o--> "+" Itinerary
EducationPlatform o--> Chat
EducationPlatform o--> "+" Excercise

Chat ..>"*" Excercise
Student <..> Chat : topic

Excercise <|-- Domain
Excercise <|-- Question 

Domain *-->"*" Application: requirements
Application -->"+" Concept

Application <|-- Correct
Application <|-- Incorrect

Question -->"+" Concept
Question -->"*" Application

Question *--> Statement
Question *--> Answer
Answer <|-- Open
Answer <|-- MultipleChoice

'Teacher ..> Open : review

Teacher ..> Topic : editor
Teacher ..> Predefined : editor
Student ...> Itinerary : reader
Student ...> Custom : editor


Topic <|.. CompositeTopic
Topic <|.. SimpleTopic
CompositeTopic o--> "+" Topic

Itinerary <|-- Custom
Itinerary <|-- Predefined

Itinerary o--> "+" Topic
'Predefined o--> "+" Topic


SimpleTopic o--> "+" Concept
SimpleTopic o--> "+" Multimedia
Concept *--> "+" Definition
Concept o--> "*" Relation

enum Relation {
    Use
    Association
    Composition
    Inheritance
    Aggregation
} 

Relation -->"+" Concept
Definition o-->"+" Justification
Justification o-->"+" Justification


Multimedia <|-- Podcast
Multimedia <|-- Video

Podcast o--> Document : transcript
Video o--> Document : transcript

Multimedia <|-- Document

Document *-->"*" Concept

@enduml