@startuml MeninasObj

!theme reddress-darkred

title Diagrama de Objetos Cuadro de las Meninas de Velázquez (Objetos)

object picture{
    + title = "La familia de Felipe IV"
    + year = 1656
    + size = Big
    + aesthetic = naturalistic
    + context
    + exhibited = El Prado Museum
}
object author{
   + name: Velázquez
}

object viewer <<PictureViewer>> {
}

object denotative  <<Narrative>>{
    + Action = retrato de la infanta Margarita Teresa de Austria...
}
object descriptive <<Narrative>>{
    + Action = painting a picture
}

picture *-- author
picture o--"0..n" viewer
picture *-- descriptive
picture *-- denotative
denotative ..> viewer

denotative *-- Model
denotative *-- Role

enum Role {
    Dog
    Infanta
    MaidOfHonor
    Painter
    Servant
    King
    Queen
}

enum Model {
    Margarita Teresa de Austria
    Velázquez
    Felipe IV
    Mariana de Austria
    ...
}

object scene {
    + lighting
    + boundaries
}

object foreground {
}
object background {
    area: nextToForeground
}
object background2 {
    area: nextToBackground
}
object imaginary {
    + area = fourthWall
}

object characterDog {
    + position = firstOnForegroundArea
    + model = homeDog
    + role = dog
    + observe(position_on_ground)
   
}

object characterProtagonist {
    + position = centerOFForegroundArea
    + model = infanta Margarita Teresa de Austria
    + role = infanta
    + observe(OutOfBoundaries)
   
}

object characterLeftOnReflection {
    + position = onMirror
    + observe(characterProtagonist.position)
}
object characterRightOnReflection {
    + position = onMirror
    + observe(characterProtagonist.position)

}

object characterKing <<SceneViewer>>{
    + position = onImaginaryAreaOnTheLeft
    + model = Felipe IV
    + role = king
    + observe(characterProtagonist.position)
   
}
object characterQueen <<SceneViewer>>{
    + position = onImaginaryAreaOnTheRight
    + model = Mariana de Austria
    + role = queen
    + observe(characterProtagonist.position)
   
}

object characterPainter {
    + position = onBackground
    + role = painter
    + observe(mirrorOutOfBoundaries)
   
}
object characterSecundary {
    + position = onBackground
    + role = MaidOfHonor, Servant
    + observe(mirrorOutOfBoundaries)
   
}

descriptive *-- scene

scene *-- foreground
scene *-- background
scene *-- background2
scene *-- imaginary

object setElementMirror {
    model: Mirror
}
object setElementPicture {
    model: BigPicture
}

foreground *-- characterProtagonist
foreground *-- characterDog
background *-- characterPainter
background *-- setElementMirror
background *-- setElementPicture
background2 *-- "n" characterSecundary
imaginary *-- characterKing
imaginary *-- characterQueen


characterPainter ..> setElementPicture

setElementMirror *-- characterLeftOnReflection
setElementMirror *-- characterRightOnReflection


characterRightOnReflection ..> characterKing :model
characterLeftOnReflection ..> characterQueen :model

characterPainter ..> author :model


@end