@startuml MeninasDomain
!theme reddress-darkred
title Modelado Cuadro de las Meninas de Velázquez

class Cuadro {
    + titulo,año,tamaño...
    + estética: naturalista
    + expuesto: contexto
}
Cuadro *-- Autor
Cuadro o--"0..n" Espectador
Cuadro *-- Narrativa

class Narrativa {

}
Narrativa <|-- Iconográfica
Narrativa <|-- Iconológica

class Iconográfica {
}
Iconográfica o-- Papel

class Papel {
    Infanta,Menina,Pintor,Sirviente,Rey,Reina...
}

class Iconológica{
}
Iconológica o-- Escena

class Escenario {
    + planos
    + iluminación
    + limites
    + cuarta_pared
}
Escena *-- Escenario
Escenario o--"0..n" Personaje
Escenario o--"0..n" ObjetoDecorado

class ObjetoDecorado {
   + posicion
   + modelo
}
ObjetoDecorado ..> Cuadro :modelo
'ObjetoDecorado ..> Puerta :modelo
ObjetoDecorado ..> Espejo :modelo


class Espejo {
    + posicion
}
Espejo o-- PersonajeReflejado

class PersonajeReflejado{
   + modelo
}
PersonajeReflejado ..> Personaje :modelo

class Personaje {
    + posicion
    + modelo
    + principal/secundario
}
Personaje ..> Autor :modelo
Personaje ..> Espectador :modelo
Personaje *-- Papel
class Espectador {
    + posicion
    + punto_de_vista
}
'Espectador <|-- Autor



@end