@startuml TuringMachineModel

'skin rose
title Modelado Maquina de Turing

class Dispositivo{
 + cambiarEstado()
}

class Escáner {
 + leer()
 + escribir()
 + moverIzquierda()
 + moverDerecha()
 + detenerse()
}

Dispositivo --> Estado

enum Estado{
+ inicial
+ borrando
+ escribiendo
+ aceptación
}

class Cinta
class Cuadrado
abstract class Simbolo

Dispositivo *--"1" Escáner
Dispositivo *--"1" Cinta 
Cinta *--"n" Cuadrado
Cuadrado o--"0..1" Simbolo
Escáner ..> Cuadrado

Simbolo <|.. Entrada
Simbolo <|.. Salida
Simbolo <|.. Blanco

class Blanco {
    + b, Δ o 0
}



'Padre <|-down- Hija : Herencia
'AbstractInterfaz <|.. Concreta : Implementacion ?
'Todo "1" *-up- "many" Parte: Composition
' o-- Agregacion
' ..> Uso
'-			private
'#			protected
'~			package private
'+			public



'Duda: Hacer diagrama de estados? de proceso?
'Duda: Los tipos de simbolos según el alfabeto de E/S: si se incluye el "simbolo especial" blanco y es dejar el cuadrado
' en blanco, no sería agregación, si no composición, ya que el estar en blanco es tener un simbolo también?
@end